#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION lib/version.py`)
ELECTRUM_DASH_VERSION=${VERSION_STRING[2]}
ELECTRUM_DASH_VERSION=${ELECTRUM_DASH_VERSION#\'}
ELECTRUM_DASH_VERSION=${ELECTRUM_DASH_VERSION%\'}
export ELECTRUM_DASH_VERSION

APK_VERSION_STRING=(`grep APK_VERSION lib/version.py`)
ELECTRUM_DASH_APK_VERSION=${APK_VERSION_STRING[2]}
ELECTRUM_DASH_APK_VERSION=${ELECTRUM_DASH_APK_VERSION#\'}
ELECTRUM_DASH_APK_VERSION=${ELECTRUM_DASH_APK_VERSION%\'}
export ELECTRUM_DASH_APK_VERSION
