#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION electrum_dash/version.py`)
DASH_ELECTRUM_VERSION=${VERSION_STRING[2]}
DASH_ELECTRUM_VERSION=${DASH_ELECTRUM_VERSION#\'}
DASH_ELECTRUM_VERSION=${DASH_ELECTRUM_VERSION%\'}
export DASH_ELECTRUM_VERSION

APK_VERSION_STRING=(`grep APK_VERSION electrum_dash/version.py`)
DASH_ELECTRUM_APK_VERSION=${APK_VERSION_STRING[2]}
DASH_ELECTRUM_APK_VERSION=${DASH_ELECTRUM_APK_VERSION#\'}
DASH_ELECTRUM_APK_VERSION=${DASH_ELECTRUM_APK_VERSION%\'}
export DASH_ELECTRUM_APK_VERSION
