#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION lib/version.py`)
ELECTRUM_DASH_VERSION=${VERSION_STRING[2]}
ELECTRUM_DASH_VERSION=${ELECTRUM_DASH_VERSION#\'}
ELECTRUM_DASH_VERSION=${ELECTRUM_DASH_VERSION%\'}
DOTS=`echo $ELECTRUM_DASH_VERSION |  grep -o "\." | wc -l`
if [[ $DOTS -lt 3 ]]; then
    ELECTRUM_DASH_APK_VERSION=$ELECTRUM_DASH_VERSION.0
else
    ELECTRUM_DASH_APK_VERSION=$ELECTRUM_DASH_VERSION
fi
export ELECTRUM_DASH_VERSION
export ELECTRUM_DASH_APK_VERSION
