FROM debian:stretch-slim
LABEL maintainer "Andriy Khavryuchenko <akhavr@khavr.com>"

RUN apt-get update -y \
    && apt-get install -y python3-pip pyqt5-dev-tools \
    && rm -rf /var/lib/apt/lists/*
