#!/usr/bin/env python

import sys
from electrum_dash import Network
from electrum_dash.util import json_encode, print_msg

try:
    addr = sys.argv[1]
except Exception:
    print "usage: get_history <dash_address>"
    sys.exit(1)

n = Network()
n.start()
h = n.synchronous_get(('blockchain.address.get_history',[addr]))
print_msg(json_encode(h))
