#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION lib/version.py`)
ELECTRUM_AXE_VERSION=${VERSION_STRING[2]}
ELECTRUM_AXE_VERSION=${ELECTRUM_AXE_VERSION#\'}
ELECTRUM_AXE_VERSION=${ELECTRUM_AXE_VERSION%\'}
export ELECTRUM_AXE_VERSION

APK_VERSION_STRING=(`grep APK_VERSION lib/version.py`)
ELECTRUM_AXE_APK_VERSION=${APK_VERSION_STRING[2]}
ELECTRUM_AXE_APK_VERSION=${ELECTRUM_AXE_APK_VERSION#\'}
ELECTRUM_AXE_APK_VERSION=${ELECTRUM_AXE_APK_VERSION%\'}
export ELECTRUM_AXE_APK_VERSION
