#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION electrum_axe/version.py`)
AXE_ELECTRUM_VERSION=${VERSION_STRING[2]}
AXE_ELECTRUM_VERSION=${AXE_ELECTRUM_VERSION#\'}
AXE_ELECTRUM_VERSION=${AXE_ELECTRUM_VERSION%\'}
export AXE_ELECTRUM_VERSION

APK_VERSION_STRING=(`grep APK_VERSION electrum_axe/version.py`)
AXE_ELECTRUM_APK_VERSION=${APK_VERSION_STRING[2]}
AXE_ELECTRUM_APK_VERSION=${AXE_ELECTRUM_APK_VERSION#\'}
AXE_ELECTRUM_APK_VERSION=${AXE_ELECTRUM_APK_VERSION%\'}
export AXE_ELECTRUM_APK_VERSION

APK_VERSION_CODE_SCRIPT='./contrib/axe/travis/calc_version_code.py'
export ELECTRUM_AXE_VERSION_CODE=`$APK_VERSION_CODE_SCRIPT`

# Check is release
SIMPLIFIED_VERSION_PATTERN="^([^A-Za-z]+).*"
if [[ ${AXE_ELECTRUM_VERSION} =~ ${SIMPLIFIED_VERSION_PATTERN} ]]; then
    if [[ ${BASH_REMATCH[1]} == ${AXE_ELECTRUM_VERSION} ]]; then
        export IS_RELEASE=y
    fi
fi
